"""Add recommendations table and unique constraint

Revision ID: c0fa636b9dfc
Revises: 2041534f503f
Create Date: 2025-06-12 07:27:42.869863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fa636b9dfc'
down_revision: Union[str, None] = '2041534f503f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'recommendations', ['cv_file_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='unique')
    # ### end Alembic commands ###
